name: Metal Scraper

on:
  schedule:
    - cron: '20 5 * * *'   # 00:20 Colombia (UTC-5)
  workflow_dispatch:

jobs:
  scraper:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install selenium pandas lxml openpyxl xlsxwriter beautifulsoup4

      - name: Install Chrome
        uses: browser-actions/setup-chrome@v1

      - name: Run scraper with retry
        env:
          METAL_USER: ${{ secrets.METAL_USER }}
          METAL_PASS: ${{ secrets.METAL_PASS }}
          EMAIL_USER: ${{ secrets.EMAIL_USER }}
          EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
        run: |

          echo "Starting scraper..."

          for i in 1 2 3
          do
            echo "Attempt $i"

            python scraper.py && break

            echo "Attempt failed. Waiting 60 seconds..."
            sleep 60
          done

          echo "Workflow finished"
