name: run-scraper

on:
  schedule:
    - cron: '0 11 * * *'
  workflow_dispatch:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:

    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install dependencies
      run: |
        pip install pandas selenium webdriver-manager lxml html5lib xlsxwriter

    - name: Setup Chrome
      uses: browser-actions/setup-chrome@v1

    - name: Run scraper
      env:
        METAL_USER: ${{ secrets.METAL_USER }}
        METAL_PASS: ${{ secrets.METAL_PASS }}
        EMAIL_USER: ${{ secrets.EMAIL_USER }}
        EMAIL_PASS: ${{ secrets.EMAIL_PASS }}
      run: python scraper.py
